services:
  - type: web
    name: ntd-trading-bot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main_render:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
